---
tblocker_log_file: "/var/log/remnanode/access.log"
tblocker_block_duration: 5
tblocker_torrent_tag: "TORRENT"
tblocker_block_mode: "nft"

tblocker_config_dir: "/opt/tblocker"
tblocker_storage_dir: "{{ tblocker_config_dir }}"
tblocker_config_file: "{{ tblocker_config_dir }}/config.yaml"
tblocker_binary_path: "{{ tblocker_config_dir }}/tblocker"

tblocker_username_regex: "email: (\\S+)"
tblocker_send_webhook: true
tblocker_webhook_url: "https://your-api-endpoint.com/webhook/ban-user"
tblocker_webhook_template: '{"username":"%s","ip":"%s","server":"%s","action":"%s","timestamp":"%s"}'
tblocker_webhook_headers: {}

tblocker_bypass_ips:
  - "127.0.0.1"
  - "::1"
